- .github/workflows/wfc_add_labels.yml
> Add github repo to CLI commands

- .github/workflows/triage.yml
- .github/workflows/wfc_add_labels.yml
- Add github repo to CLI commands
- Test a more complex triage command
> testAction

- .github/workflows/wfc_add_labels.yml
> Fix escaping of comments

- .github/workflows/wfc_add_labels.yml
> Fix escape some more in the action

- .github/workflows/triage.yml
> Make triage task ordinary

- .github/workflows/lifecycle.yml
- .github/workflows/triage.yml
- .github/workflows/wfc_add_labels.yml
- .github/workflows/wfc_stale_issues.yml
- Make triage task ordinary
- Add a workflow to deal with issue lifecycle
> lifecycleActions

- .github/workflows/lifecycle.yml
> Switch to workflow_dispatch instead of repository dispatch

- .github/workflows/lifecycle.yml
- .github/workflows/wfc_stale_issues.yml
> Add shorter timespan to check if it works

- .github/workflows/wfc_add_labels.yml
- .github/workflows/wfc_stale_issues.yml
> Improve output of lifecycle job

- .github/workflows/wfc_stale_issues.yml
> Add autoclose labels and comment as parameters to lifecycle

- .github/workflows/wfc_stale_issues.yml
> Avoid adding tags and comment to issue already tagged as staled

- .github/workflows/wfc_stale_issues.yml
> Fix typo in lifecycle workflow

- .github/workflows/wfc_lifecycle.yml
> Fix typo in workflow

- .github/workflows/wfc_lifecycle.yml
> Fix broken trigger for workflow_dispatch

- .github/workflows/wfc_lifecycle.yml
- labels.yml
- org_labels.yml
> Add an action to sync labels between conf and github

- org_labels.yml
> Reduce description size

- .github/workflows/lifecycle.yml
- labels.yml
- org_labels.yml
> remove test tag and improve color scheme

- .github/workflows/lifecycle.yml
- PROJECT_MANAGEMENT.md
- labels.yml
> Add PROJECT_MANAGEMENT process and link to invite

- .github/workflows/wfc_lifecycle.yml
> Add job to sync files from .github repo

- .github/workflows/wfc_lifecycle.yml
> Make labelSync a separate job

- .github/workflows/wfc_lifecycle.yml
> Fix bad file in filesToSync lifecycle action

- CONTRIBUTING.md
> Fix link in contributing

- PROJECT_MANAGEMENT.md
> Add useful github search urls for triage

- org_labels.yml
> Add kind/improvement and breaking-changes to standard labels

- .github/workflows/wfc_lifecycle.yml
- org_labels.yml
> Improve commit message from action that copies files

- .github/workflows/wfc_lifecycle.yml
> fix: correct sync action to replace file content not append

- .github/workflows/wfc_lifecycle.yml
> Update commit message

- .github/workflows/wfc_lifecycle.yml
> fix(.github): Correct PR in sync job

- .github/workflows/wfc_lifecycle.yml
- SECURITY.md
> docs: Add a security policy to all repos

- .github/workflows/wfc_lifecycle.yml
> fix(.github): don't comment about closing on already closed issues

- .github/workflows/wfc_lifecycle.yml
> ci: remove triage/pending labels on closed tickets

- .github/workflows/wfc_lifecycle.yml
> ci(github): fix bad variable in lifecycle actions

- .github/workflows/wfc_lifecycle.yml
> Fix github-pm-groomer install

- .github/workflows/wfc_lifecycle.yml
> fix: missing quote on lifecycle workflow

- .github/workflows/wfc_lifecycle.yml
> fix: remove quotes in open issue job

- .github/workflows/wfc_lifecycle.yml
This might be the problem to our failing action
> fix: don't use `${{}}` syntax in `if` action

- .github/workflows/wfc_lifecycle.yml
> fix: escape ! which has some meaning in yaml

- PROJECT_MANAGEMENT.md
> chore: clarify what needs to be done with `triage/stale` issues.

- .github/workflows/wfc_lifecycle.yml
See https://github.com/kumahq/kuma/issues/4606
It's not supported in `gh` yet.
> feat(lifecycle): close issues as not planned

- SECURITY.md
https://github.com/kumahq/kuma/pull/5536 causing https://github.com/kumahq/kuma/pull/5544
> docs(SECURITY.md): update to use GH's reports

- .github/workflows/pr-checklist.yaml
- .github/workflows/pr-management.yaml
- .github/workflows/wfc_pr_management.yml
This workflow can be used for these things:
- Replace mergify for auto-merge/auto-approve based on labels
- Add a comment to a PR (can be used for checklists)
> feat(.github): add pr_management workflow

- .github/workflows/wfc_lifecycle.yml
It doesn't really change and it's simple enough to copy from one repo to another
> ci: don't sync lifecycle.yml

- .github/workflows/wfc_pr_management.yml
> ci(auto-merge): add optional approve token

- .github/workflows/wfc_pr_management.yml
> ci(auto-merge): reduce action verbosity

- CONTRIBUTING.md
> docs(links): fix chat link

- CONTRIBUTING.md
> Fix chat kuma io 2

- .github/workflows/wfc_lifecycle.yml
- CODEOWNERS
- org_labels.yml
Also add the possibility to ignore files to sync
> feat: sync milestones and CODEOWNERS in all repos

- meta_org.yml
Add releases through 2.6 to milestones
> additional releases

- .github/workflows/wfc_backport.yml
Better that it's the same as `github-app-token`
> feat(backport): rename appId to app_id and appPrivateKey to private_key

- .github/workflows/wfc_lifecycle.yml
- CODEOWNERS
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- GOVERNANCE.md
- SECURITY.md
We should use this everywhere and folks can explicitly ignore if they diverge
> chore: update synced files

- meta_org.yml
Add `kind/service-review` label
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits): 👍 
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?: 👍
> chore: add `kind/service-review` label

- .github/workflows/wfc_lifecycle.yml
> ci(lifecycle): add possibility to use github app for PR

- .github/dependabot.yml
Enable dependabot
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits): 👍 
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?: 👍
> ci(dependabot): add dependabot configuration

- .github/workflows/wfc_backport.yml
> Revert "ci(backport): make the backport job carry over the labels from the main PR"

- .github/ISSUE_TEMPLATE/bug-report.yml
Update Kuma repo issue report template
> update issue report template

- GOVERNANCE.md
Document the process for the new Kuma maintainers application.
xref: https://github.com/kumahq/kuma/pull/12956
Supplement the CNCF maintainers' information update process
> chore(community): update governance.md

- .github/workflows/wfc_lifecycle.yml
we don't need to stale service review issues and needs-reproducing issues
> feat(ci): don't stale service-review and needs-reproducing

- .github/workflows/wfc_lifecycle.yml
github secret names are case-sensitive and all secretes by default are upper case
> fix(lifecycle): change generate github token action to official github action

- .github/workflows/wfc_lifecycle.yml
> fix(lifecycle): fix secret typo
